home/urls.py
from django.conf.urls import url


app_name = 'home'

urlpatterns = [

]

post/urls.py
from django.conf.urls import url
from django.urls import path
from post.views import moderation, post_edit, post_detail, add_comment

app_name = 'post'

urlpatterns = [
    path(r'moderation/', moderation, name='moderation'),
    path(r'<int:pk>/', post_detail, name='post_detail'),
    path(r'<int:pk>/edit/', post_edit, name='post_edit'),
    path(r'comment/<int:article_id>/', add_comment, name='add_comment'),
]

yordam/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from user.views import RegisterFormView
from user.views import LoginFormView
from home.views import home
from django.conf import settings
from django.conf.urls.static import static
from post.views import add
from user.views import user_logout

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'register/', RegisterFormView.as_view(), name='register'),
    path(r'login/', LoginFormView.as_view(), name='login'),
    path(r'', home, name='home'),
    path(r'add', add, name='add'),
    path(r'thanks', home, name='thanks'),
    path(r'post/', include('post.urls')),
    path(r'logout/', user_logout, name='logout')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models


class Location(models.Model):
    city = models.CharField("Город ", max_length=30)
    country = models.CharField("Страна ", max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return self.city

home/forms.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    email = forms.CharField(max_length=255, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username = email , password=password)
        print(email, password)
        if not user or not user.is_active:
            raise forms.ValidationError("Неверный логин или пароль.")
        return self.cleaned_data

    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username = email , password=password)
        return user

home/views.py
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect

from home.forms import LoginForm
from post.models import Post

app_name = 'home'


def home(request):
    template_name = 'home.html'
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            return redirect('home')  # Redirect to a success page.

    post = Post.objects.filter(post_status=1)
    return render(request, template_name, context={'posts': post, 'form': form})

home/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="shortcut icon" href="{% static "img/favicon.png" %}" type="image/x-icon">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|Roboto+Slab" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.css" %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>

<body class="grey lighten-3">

    <!--Main Navigation-->
    <header>
    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100 font-weight-bold">Авторизация</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <ul class='form-errors' style="color: red;">
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                <div class="modal-body mx-3">
                    <div class="md-form mb-5">
                        <i class="fa fa-envelope prefix grey-text"></i>
                        <input type="text" name='email' class="form-control validate">
                        <label data-error="wrong" data-success="right">Логин</label>
                    </div>

                    <div class="md-form mb-4">
                        <i class="fa fa-lock prefix grey-text"></i>
                        <input type="password" name = 'password' id="defaultForm-pass" class="form-control validate">
                        <label data-error="wrong" data-success="right" for="defaultForm-pass">Пароль</label>
                    </div>

                </div>

                <div class="modal-footer d-flex justify-content-center">
                        <button type="submit" class="btn success-color" name="LoginButton" value="1">Войти</button>
                </div>
                </form>
            </div>
        </div>
    </div>


        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar success-color">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href={% url 'home' %}>
                    <strong class="white-text">Yordam</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link waves-effect white-text" href={% url 'home' %}>Главная
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect white-text" href="https://mdbootstrap.com/material-design-for-bootstrap/" target="_blank">Перевозка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect white-text" href="https://mdbootstrap.com/getting-started/" target="_blank">События</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect white-text" href="https://mdbootstrap.com/getting-started/" target="_blank">Мемы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect white-text" href="https://mdbootstrap.com/bootstrap-tutorial/" target="_blank">Прочее</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav nav-flex-icons">
                        <li style="margin-right: 6px" class="nav-item">
                            <a href="{% url 'add' %}" class="nav-link border border-light rounded waves-effect success-color white-text"
                                >
                                <i class="fa fa-check"></i>Оставить заявку
                            </a>
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <!--Dropdown primary-->
                                <div class="dropdown">

                                    <!--Trigger-->
                                    <div class="avatar mx-auto dropdown-toggle white-text"  id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static "img/ava.png" %}" alt="avatar mx-auto" width="50" height="50" class="rounded-circle img-fluid white-text">
                                    </div>

                                    <!--Menu-->
                                    <div class="dropdown-menu dropdown-success">
                                        <a class="dropdown-item" href="#">Профиль</a>
                                        <a class="dropdown-item" href="#">Уведомления</a>
                                        <a class="dropdown-item" href="#">Настройки</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href={% url 'logout' %}>Выйти</a>
                                    </div>
                                </div>
                                <!--/Dropdown primary-->
                                </li>

                            {% else %}
                                <a href="{% url 'login' %}" class="nav-link border border-light rounded waves-effect success-color white-text">
                                    <i class="fa fa-user-o pr-2"></i>Авторизация
                                </a>
                            {% endif %}
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
        <!-- Navbar -->

    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main class="mt-5 pt-5">
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="page-footer text-center font-small success-color mt-4">

        <hr class="my-4">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="https://www.facebook.com/mdbootstrap" target="_blank">
                <i class="fa fa-facebook mr-3 fa-lg"></i>
            </a>

            <a href="https://vk.com/" target="_blank">
                <i class="fa fa-vk mr-3 fa-lg"></i>
            </a>

            <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
                <i class="fa fa-youtube mr-3 fa-lg"></i>
            </a>
            <a href="" >
                <button type="button" class="border border-light rounded waves-effect success-color white-text">Написать Админу</button>
            </a>

        </div>
        <!-- Social icons -->

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2018 Copyright
        </div>
        <!--/.Copyright-->

    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static "js/mdb.min.js" %}" ></script>
    <!-- Initializations -->
    <script type="text/javascript">
        $(document).ready(function(){
            $('#other').hide();
            $('#id_article_section').on('change', function() {
                if (this.value == '1' ) {
                    $('#other').show();
                }
                else {
                    $('#other').hide();
                }
            });
        });
    </script>
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>
</body>

</html>

home/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
Главная Страница
{% endblock %}

{% block content %}
    <!--Cards-->
            <div class="row mb-4 wow fadeIn">

                <div class="col-md-8">
                    {% for post in posts %}
                    <!-- Blog Post -->
                      <div class="card mb-1" style="margin-top: 25px">
                          <a href="{% url 'post:post_detail' post.id %}"> <img class="card-img-top" src="media/{{ post.post_photo }}" alt="Card image cap"> </a>
                        <div class="card-body">
                            <small class="text-muted float-right">{{ post.post_date }}</small>

                            <ul class="list-inline mb-0">
                                <li class="list-inline-item m-0">
                                    <div class="avatar mx-auto white"><img src="{% static "img/ava.png" %}" alt="avatar mx-auto white" width="50" height="50" class="rounded-circle img-fluid">
                                    </div>
                                </li>
                                <li class="list-inline-item m-0"><a class="" href=""><strong>{{ post.post_author }}</strong></a>
                                </li>
                            </ul>
                            <hr>
                            <div class="row">
                                <div class="col-md-8">
                                    <h4 class="card-title" style="font-family: 'Roboto Condensed', sans-serif; margin-left: 10px"> <strong><a href="{% url 'post:post_detail' post.id %}"> {{ post.post_title }} </a> </strong></h4>
                                </div>
                            </div>
                          <p class="card-text" style="font-family: 'Roboto', sans-serif; margin-left: 10px">{{ post.post_content }} </p>

                        </div>
                        <div class="card-footer">
                          <a href="#" class="btn success-color">Комментировать &rarr;</a>
                        </div>
                      </div>
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    <!-- Search Widget -->
                    <div class="card my-4">
                        <h5 class="card-header success-color white-text">Лучшее за неделю</h5>
                        <div >
                          <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Нужно отправить документы !Срочно
                                <span class="badge badge-primary badge-pill">14</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Концерти Шабнами Сурайё
                                <span class="badge badge-primary badge-pill">12</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Динг динг донг
                                <span class="badge badge-primary badge-pill">1</span>
                            </li>
                        </ul>
                        </div>
                      </div>
                    <div class="card my-4">
                        <h5 class="card-header success-color white-text">Интересные видео</h5>
                        <div class="card-body">
                            <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/HhRUCg2BNx8" allowfullscreen></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="card my-4">
                        <h5 class="card-header success-color white-text">Поиск</h5>
                        <div class="card-body">
                          <div class="input-group">
                            <input type="text" class="form-control" placeholder="Искать...">
                            <span class="input-group-btn">
                              <button class="btn success-color" type="button">Нажми!</button>
                            </span>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
{% endblock content %}