home/urls.py
from django.conf.urls import url


app_name = 'home'

urlpatterns = [

]

post/urls.py
from django.conf.urls import url
from django.urls import path
from post.views import moderation, post_edit, post_detail, add_comment

app_name = 'post'

urlpatterns = [
    path(r'moderation/', moderation, name='moderation'),
    path(r'<int:pk>/', post_detail, name='post_detail'),
    path(r'<int:pk>/edit/', post_edit, name='post_edit'),
    path(r'comment/<int:article_id>/', add_comment, name='add_comment'),
]

yordam/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from user.views import RegisterFormView
from user.views import LoginFormView
from home.views import home
from django.conf import settings
from django.conf.urls.static import static
from post.views import add
from user.views import user_logout

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'register/', RegisterFormView.as_view(), name='register'),
    path(r'login/', LoginFormView.as_view(), name='login'),
    path(r'', home, name='home'),
    path(r'add', add, name='add'),
    path(r'thanks', home, name='thanks'),
    path(r'post/', include('post.urls')),
    path(r'logout/', user_logout, name='logout')
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField


class Section(models.Model):
    class Meta:
        db_table = 'section'

    section_title = models.CharField(max_length=200)
    section_url = models.CharField(max_length=50)
    section_description = models.TextField()

    def __str__(self):
        return self.section_title


class Post(models.Model):
    class Meta:
        db_table = "Post"

    post_title = models.CharField("Заголовок", max_length=100)
    post_section = models.ForeignKey(Section, related_name="Категория", on_delete=models.CASCADE, )
    post_author = models.ForeignKey(User, related_name="Автор", on_delete=models.CASCADE, )
    post_date = models.DateTimeField('Дата публикации', default=timezone.now)
    # content = RichTextField("Ваша Заявка")
    post_content = models.TextField("Ваша Заявка")
    post_photo = models.ImageField("Фото", upload_to='photo', blank=True)
    post_status = models.IntegerField("Статус")
    post_visits = models.IntegerField("Количество Посещений", default=0)
    post_likes = models.IntegerField("Лайки", default=0)

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('post:post_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        print(self.post_photo, self.post_content, self.post_section.id)
        if not self.post_photo:
            self.post_photo = 'category/{}.png'.format(self.post_section.id)
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    class Meta:
        db_table = "comments"

    # path = ArrayField(models.IntegerField())
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, )
    author_id = models.ForeignKey(User, on_delete=models.CASCADE, )
    content = models.TextField('Комментарий')
    pub_date = models.DateTimeField('Дата комментария', default=timezone.now)

    def __str__(self):
        return self.content[0:200]

post/forms.py
from django import forms

from .models import Post, Section, Comment


class PostForm(forms.ModelForm):
    # article_title = forms.CharField(max_length=100)
    # article_section = forms.ModelChoiceField(queryset=Section.objects.all(), empty_label=None)
    # article_content = forms.TextField()
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['post_title'].widget.attrs = {'class': 'form-control form-control-lg',
                                                     'placeholder': "Заголовок*"}
        self.fields['post_title'].label = ''

        self.fields['post_section'].widget.attrs = {'class': 'custom-select'}
        self.fields['post_section'].label = 'Выберите Категорию*'

        self.fields['post_content'].widget.attrs = {'class': 'form-control rounded-0', 'rows': "10",
                                               'placeholder': "Ваша Заявка*"}
        self.fields['post_content'].label = ''

    class Meta:
        model = Post
        fields = ['post_title', 'post_section', 'post_photo', 'post_content']


class CommentForm(forms.Form):
    comment_area = forms.CharField(
        label="",
        widget=forms.Textarea
    )

post/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils import timezone

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView
from django.views.generic import DetailView

from post.models import Post, Comment
from post.forms import PostForm, CommentForm

app_name = 'post'


def add(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.post_author = request.user
            post.post_date = timezone.now()
            post.post_status = 0
            post.save()
            return redirect('post:post_detail', post.pk)
    else:
        form = PostForm()
    return render(request, 'add.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.post_date = timezone.now()
            post.save()
            return redirect('post:post_detail', post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'edit.html', {'form': form})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'GET' and post.post_author != request.user and post.post_status == 1:
        post.post_visits += 1
        post.save()

    if (request.GET.get('DeleteComment')):
        Comment.objects.filter(id=request.GET.get('DeleteComment')).delete()
        return redirect('post:post_detail', post.id)

    context = {}
    context['post'] = post
    context['comments'] = post.comment_set.all()
    comment_form = CommentForm
    context['form'] = comment_form

    return render(
        request,
        'post_detail.html',
        context=context
    )


def moderation(request):
    post = Post.objects.filter(post_status=0)
    if (request.GET.get('DeleteButton')):
        Post.objects.filter(id=request.GET.get('DeleteButton')).delete()
        return redirect('post:moderation')

    if (request.GET.get('checked')):
        post = Post.objects.get(id=request.GET.get('checked'))
        post.post_status = 1
        post.save()
        return redirect('post:moderation')
    return render(request, 'moderation.html', {'post': post})


@login_required
@require_http_methods(["POST"])
def add_comment(request, article_id):
    form = CommentForm(request.POST)
    post = get_object_or_404(Post, id=article_id)

    if form.is_valid():
        comment = Comment()
        comment.path = []
        comment.post_id = post
        comment.author_id = auth.get_user(request)
        comment.content = form.cleaned_data['comment_area']
        comment.save()

    return redirect(post.get_absolute_url())

post/templates/add.html
{% extends 'base.html' %}

{% block title %}
Добавить заявку
{% endblock %}

{% block content %}
        <div class="container">
        <div class="card">
            <div class="card-body">
        <h1 align="center">Отправить Заявку</h1>
        <form enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            {{ form.as_p}}
{#            <div id="other">#}
{#                <div class="form-group">#}
{#                    <input class="form-control form-control-lg" type="text" placeholder="Цена за доставку">#}
{#                </div>#}
{#            </div>#}
            <button type="submit" class="btn success-color"> Отправить </button>
        </form>
            </div>
        </div>
        </div>
{#    </div>#}
{% endblock content %}

post/templates/edit.html
{% extends 'base.html' %}

{% block title %}
Изменить завяку
{% endblock %}

{% block content %}
        <div class="container">
        <div class="card">
            <div class="card-body">
        <h1 align="center">Изменить Заявку</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p}}
{#            <div id="other">#}
{#                <div class="form-group">#}
{#                    <input class="form-control form-control-lg" type="text" placeholder="Цена за доставку">#}
{#                </div>#}
{#            </div>#}
            <button type="submit" class="btn success-color"> Отправить </button>
        </form>
        </div>
        </div>
        </div>
{#    </div>#}
{% endblock content %}

post/templates/moderation.html
{% extends 'base.html' %}

{% block title %}
Добавить заявку
{% endblock %}

{% block content %}
    <table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Заголовок</th>
            <th>Дата</th>
            <th>Пользователь</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for p in post %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href={% url 'post:post_detail' p.pk %}> {{ p.post_title }}</a> </td>
            <td>{{ p.post_date}}</td>
            <td>{{ p.post_author }}</td>
            <td>
                <form action="" method="get">
                    <button class="btn success-color white-text" name="checked" value="{{ p.id }}"><i class="fa fa-check"></i></button>
                    <a class="btn success-color white-text" href={% url 'post:post_edit' p.pk %}><i class="fa fa-pencil"></i></a>
                    <button class = "btn success-color white-text" name="DeleteButton" value="{{ p.id }}"><i class="fa fa-times"></i></button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

post/templates/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ post.post_title }}
{% endblock %}

{% block content %}
    <div class="row mb-4 wow fadeIn">
                <div class="col-md-8">
                    <!-- Blog Post -->
                      <div class="card mb-1">
                        <img class="card-img-top" src="{{ post.post_photo.url }}" alt="Card image cap">
                        <div class="card-body">
                            {% if user.is_authenticated and user == post.post_author %}
                                    <a class="btn float-right success-color white-text" href={% url 'post:post_edit' post.id %}><i class="fa fa-pencil"></i></a>
                            {% endif %}
                            <small class="text-muted float-right">{{ post.post_date }} </small>

                            <ul class="list-inline mb-0">
                                <li class="list-inline-item m-0">
                                    <div class="avatar mx-auto white"><img src="{% static "img/ava.png" %}" alt="avatar mx-auto white" width="50" height="50" class="rounded-circle img-fluid">
                                    </div>
                                </li>
                                <li class="list-inline-item m-0"><a class="" href=""><strong>{{ post.post_author }}</strong></a>
                                </li>
                            </ul>
                            <hr>
                            <div class="row">
                                <div class="col-md-8">
                                    <h4 class="card-title"> <strong><a href="{% url 'post:post_detail' post.id %}"> {{ post.post_title }} </a> </strong></h4>
                                </div>
                            </div>
                          <p class="card-text">{{ post.post_content }} </p>

                        </div>
                        <div class="card-footer">
                          <a href="#" class="btn success-color">Комментировать &rarr;</a>
                        </div>
                      </div>
                <h2 style="margin-top: 50px">Комментарии</h2>
                {% for comment in comments %}
                    <div class="card mb-2">
                        <div class="card-body">
                            {% if user.is_authenticated and user == comment.author_id %}
                                <form action="" method="get">
                                <button  onclick="clicked(event)" class = "success-color float-right" name="DeleteComment" value="{{ comment.id }}"><i class="fa fa-times"></i></button>
                                <script>
                                    function clicked(e)
                                    {
                                        if(!confirm('Вы уверены?'))e.preventDefault();
                                    }
                                    </script>
                                </form>
                            {% endif %}
                            <small class="text-muted float-right">{{ comment.pub_date }} </small>
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item">
                            <div class="avatar mx-auto white"><img src="{% static "img/ava.png" %}" alt="avatar mx-auto white" width="50" height="50" class="rounded-circle img-fluid">
                            </div>
                                </li>

                                <li class="list-inline-item">
                                    <strong>{{ comment.author_id.get_full_name|default:comment.author_id.username }}</strong>&nbsp;&nbsp;
                                </li>
                            </ul>
                                    <div class="card-text" style="margin-left: 60px">
                                    <p>{{ comment.content|safe }}</p>
                                </div>
                        </div>
                        </div>
                {% endfor %}
                {% if not form %}
{#                    <h3 >Написать комментарий</h3>#}
{#                    <form action="{% url 'post:add_comment' article.id %}" method="post">#}
{#                    {% csrf_token %}#}
{#                    {% form %}#}
{#                        <button type="submit" class="btn btn-primary">Комментировать</button>#}
{#                    </form>#}

                {% else %}
                    <div class="panel panel-warning">
                        <div class="panel-body">
                            Только авторизованные пользователи могут оставлять комментарии.<br />
                        </div>
                    </div>
                {% endif %}
                </div>
                <div class="col-md-4">
                    <!-- Search Widget -->
                      <div class="card my-4">
                        <h5 class="card-header">Поиск</h5>
                        <div class="card-body">
                          <div class="input-group">
                            <input type="text" class="form-control" placeholder="Искать...">
                            <span class="input-group-btn">
                              <button class="btn success-color" type="button">Нажми!</button>
                            </span>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
{% endblock %}